kind: ext-action
method: POST
path: /ext/settings/parents/
action: setWaitingListApplicationContactGroup
summary: Set the waiting list contact group
tags: [ Settings ]
source:
  request: inferred
  response: inferred
body:
  params:
    section_id:
      type: string
    group:
      type: string
      description: Contact group.
response:
  schema:
    $ref: SettingsStatusResponseData
  envelope: true
sources: [ area.settings.f73c3ef434f40520f0bc.js ]
